### PR TITLE
Interpreter tests, reorganized file structure, interpreter with an output stream

### PR DESCRIPTION
**Pull request by maax3v3**
Hello, I saw this project on your Reddit post. I am fairly new to contributing on open source projects, and to Rust, and I thought it would be a good idea to contribute to Neko.

This PR includes :

- Addition of tests for the interpreter: This ensures that the interpreter is functioning correctly. More tests can be added when other features are added or when existing features are changed.
- Improved output stream support: The interpreter now has the ability to print to any output stream, which provides more flexibility for the end user.
- Reorganized source structure: The source code has been rearranged with a *lib.rs* file and an *interpreter.rs* module

Please let me know if there are any additional changes or modifications required. I am new to the open source world and would appreciate any feedback on my contribution.

### CODE REVIEW

**Review by ladroid — APPROVED** [review]
Hello,

Haven't been able to see it before, but in general, everything is fine. Thanks for the help, these changes are very helpful.

**Comment by maax3v3** [comment]
Thank you for your feedback. Please let me know if there is another feature I could contribute to

**Comment by ladroid** [comment]
Hello, 

If you are interested in the project then [there are some tasks](https://github.com/users/ladroid/projects/2) that I am going to implement (it's not a full list), you can also put your ideas or suggestions as well.

P.S.
I am using Discord (if you have I can create a group and will paste it into README) so we can communicate there if you wish

**Comment by maax3v3** [comment]
Hello, yes I have Discord. You can create a Discord server/group for the project.

**Comment by ladroid** [comment]
Hello, 
Sorry, for the late reply this is a Discord server -> https://discord.gg/FfAYhv33

If there are some questions or suggestions don’t hesitate to write

**Comment by maax3v3** [comment]
Hello, no worries, I too will be busy outside of weekends. The invite link seems to be invalid

**Comment by ladroid** [comment]
Hello, that's okay I am also not always available. 

Resend the link https://discord.gg/GPU7KXchYQ

**Pull request merged**
